"""add fcm_token to users

Revision ID: c4a0cd407830
Revises: 295f1c220992
Create Date: 2026-06-24 22:53:53.885003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4a0cd407830'
down_revision: Union[str, Sequence[str], None] = '295f1c220992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('refresh_tokens')
#     op.alter_column('blacklisted_tokens', 'blacklisted_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('daily_summaries', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('daily_summaries', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('devices', 'installed_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.drop_constraint(op.f('devices_device_id_key'), 'devices', type_='unique')
#     op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
#     op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
#     op.alter_column('events', 'timestamp',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.drop_column('events', 'severity')
#     op.alter_column('failed_attempts', 'last_attempt',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('networks', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.drop_constraint(op.f('networks_network_id_key'), 'networks', type_='unique')
#     op.drop_index(op.f('ix_networks_network_id'), table_name='networks')
#     op.create_index(op.f('ix_networks_network_id'), 'networks', ['network_id'], unique=True)
#     op.alter_column('readings', 'received_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.drop_index(op.f('ix_readings_device_ts_desc'), table_name='readings')
#     op.create_index('ix_readings_device_ts_desc', 'readings', ['device_id', 'timestamp'], unique=False)
#     op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
#     op.alter_column('users', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('users', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
#     op.drop_index(op.f('ix_users_email'), table_name='users')
#     op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
#     op.alter_column('valve_logs', 'commanded_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('zones', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('zones', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('valve_logs', 'commanded_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.drop_index(op.f('ix_users_email'), table_name='users')
#     op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
#     op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
#     op.alter_column('users', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('users', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.drop_column('users', 'fcm_token')
#     op.drop_index('ix_readings_device_ts_desc', table_name='readings')
#     op.create_index(op.f('ix_readings_device_ts_desc'), 'readings', ['device_id', sa.literal_column('timestamp DESC')], unique=False)
#     op.alter_column('readings', 'received_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.drop_index(op.f('ix_networks_network_id'), table_name='networks')
#     op.create_index(op.f('ix_networks_network_id'), 'networks', ['network_id'], unique=False)
#     op.create_unique_constraint(op.f('networks_network_id_key'), 'networks', ['network_id'], postgresql_nulls_not_distinct=False)
#     op.alter_column('networks', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('failed_attempts', 'last_attempt',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.add_column('events', sa.Column('severity', sa.VARCHAR(length=10), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False))
#     op.alter_column('events', 'timestamp',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
#     op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=False)
#     op.create_unique_constraint(op.f('devices_device_id_key'), 'devices', ['device_id'], postgresql_nulls_not_distinct=False)
#     op.alter_column('devices', 'installed_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('daily_summaries', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('daily_summaries', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('blacklisted_tokens', 'blacklisted_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.create_table('refresh_tokens',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('token_hash', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
#     sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
#     sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
#     )
#     # ### end Alembic commands ###

def upgrade() -> None:
    """Upgrade schema."""
    # Only add the fcm_token column to users table
    op.add_column('users', sa.Column('fcm_token', sa.String(length=500), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # Rollback column addition if needed
    op.drop_column('users', 'fcm_token')