// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJk4H7Gj6fovVNYcsw6Yo5guPXQx9QCLA',
    appId: '1:987459520382:web:e84c0c94b6ec1ff100d52f',
    messagingSenderId: '987459520382',
    projectId: 'aquasense-5c86f',
    authDomain: 'aquasense-5c86f.firebaseapp.com',
    storageBucket: 'aquasense-5c86f.firebasestorage.app',
    measurementId: 'G-HS4G2ZY7WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChr8PrIOP_i6aPPCm2AlyuDPdS-dyPkTU',
    appId: '1:987459520382:android:4468b037b3c1f50500d52f',
    messagingSenderId: '987459520382',
    projectId: 'aquasense-5c86f',
    storageBucket: 'aquasense-5c86f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpfVdHfsJ8czwk4Ih54NK3gJyxNnBTy4k',
    appId: '1:987459520382:ios:c6e1925d9b00060d00d52f',
    messagingSenderId: '987459520382',
    projectId: 'aquasense-5c86f',
    storageBucket: 'aquasense-5c86f.firebasestorage.app',
    androidClientId: '987459520382-8g6t2sfvp4cjoo3u64v1ek8kvd13megi.apps.googleusercontent.com',
    iosClientId: '987459520382-2aktld0uibqslt7b5elahmc7d66vac43.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquaSense',
  );
}
